# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mather.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmather.proto\x12\x05proto\"\x1e\n\x0cMathResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\"#\n\x0bMathRequest\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x32;\n\x06Mather\x12\x31\n\x06\x44oMath\x12\x12.proto.MathRequest\x1a\x13.proto.MathResponseB\x0eZ\x0cproto/matherb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mather_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014proto/mather'
  _MATHRESPONSE._serialized_start=23
  _MATHRESPONSE._serialized_end=53
  _MATHREQUEST._serialized_start=55
  _MATHREQUEST._serialized_end=90
  _MATHER._serialized_start=92
  _MATHER._serialized_end=151
# @@protoc_insertion_point(module_scope)
